name: CI
on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --no-progress --non-interactive
      
      - name: Lint
        run: yarn lint
      
      - name: Test coverage
        run: yarn test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run release scripts
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${REPOSITORY}
          yarn release
        env:
          USER_NAME: 'github-actions[bot]'
          USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
